### ISSUE TITLE
Nombre de proveedor en Board File Description

### ISSUE THREAD

**Issue by gguichal** [ciaa/CIAA_ACC#2]
Propongo cambiar nombre de proveedor a "CIAA Project", o algo así y no dejar el url como nombre del proveedor. Me gusta el CIAA al inicio en vez de "Proyecto CIAA", pero podría también ser eso otro.

**Comment by nscotti** [comment]
Listo! Ya edité el archivo board.xml.

**Comment by martinribelotta** [comment]
@nscotti cuando hagas un commit y que sea la solución a un bug, agrega la frase "fix #<el numbero del commit>" asi github lo cierra automaticamente.

Por ejemplo, un commit que cierre esta issue seria:

Fix name on board.xml, this fix #2

**Comment by nscotti** [comment]
Gracias!
