### ISSUE TITLE
Board Definition File mods for Vivado 2019.1

### ISSUE THREAD

**Issue by gguichal** [ciaa/CIAA_ACC#5]
Spaces in Vendor field in board.xml seem to break synthesis for Vivado 2019.1. I made ir work with CIAA-Prokject, but we should define somethng that works and keep it.

Options I can tink of... A simple "CIAA", "CIAA-Project", "CIAA.Project"... I don't care as long it's a good for marketing  the project and works :-)

Schema 2.1 doesnt seem to be defined in Vivado\2019.1\data\boards\board_schemas\
  Only 1.0, 1.1 and 2.0.... I think schema in board.xml should  be 2.0

**Comment by rodrigomelo9** [comment]
Please, if you have it solved, made a pull request with the solution :-D

**Comment by rodrigomelo9** [comment]
I was using the bdf of the new repo, CIAA-Project name is not specified in any place and it works (bitstream generation without problems). It was using Vivado 2019.2.

In the 2019.2 version, boards_schemas do not exists. I assume that this directory was not in use.
Moreover, if you check the [XilinxBoardStore](https://github.com/Xilinx/XilinxBoardStore/) there are boards using 2.1 and also in the UG895 is said: *Identifies the schema version of the board file. The latest version of the schema is 2.1.*

@gguichal I think that this is issue can be closed, or instead, more information is needed to be reproduced.

**Comment by rodrigomelo9** [comment]
I checked with 2019.1 and is also working there (bitstream generation without errors). In both cases, 2019.1 and 2, it was running Vivado under a Linux (Debian).

**Comment by rodrigomelo9** [comment]
I found the problem. In #2 @gguichal proposed to change *vendor* to *CIAA Project* and @nscotti did it. It seems that that commit was lost... However, the doc (ug895) says: 
> Web address of the board provider (example xilinx.com)
So, it was wrong to change the vendor field. Closed.
